package com.application.WorkManagement.enums;

public enum ActivityType {
    SET_DEADLINE,
    CHANGE_DEADLINE,
    DELETE_DEADLINE,
    REMINDER_DEADLINE,
    CREATE_CARD,
    DELETE_CARD,
    CREATE_CATEGORY,
    DELETE_CATEGORY,
    CHANGE_SCOPE_TABLE,
    NOTIFICATION_DEADLINE
}
